spring.application.name=iceops-api-gateway
server.port=8080

eureka.client.service-url.defaultZone=http://quantik-eureka-server:8761/eureka

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true