spring.application.name=ICEOPS-AUTH-SERVICE
server.port=8081

spring.datasource.url=jdbc:mysql://host.docker.internal:3306/iceops_auth
spring.datasource.username=root
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://quantik-eureka-server:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true